export const Questions = [
	{
		id: 1,
		prompt: "Which of this is not a javascript framework?",
		optionA: "React",
		optionB: "Angular",
		optionC: "Vue",
		optionD: "Java",
		asnwer: "optionD",
	},
	{
		id: 2,
		prompt: "What command can you use to generate a React project??",
		optionA: "react-starter",
		optionB: "create-react-app",
		optionC: "react-gen",
		optionD: "react-start",
		asnwer: "optionB",
	},
	{
		id: 3,
		prompt: "What syntax do you use to create a component in React?",
		optionA: "a generator",
		optionB: "a function or a class",
		optionC: "a service worker",
		optionD: "a tag",
		asnwer: "optionB",
	},
	{
		id: 4,
		prompt: "To create a constant in JavaScript, which keyword do you use??",
		optionA: "const",
		optionB: "let",
		optionC: "constant",
		optionD: "var",
		asnwer: "optionA",
	},
	{
		id: 5,
		prompt: "What is the JavaScript syntax extension that is commonly used to create React elements?",
		optionA: "HTML",
		optionB: "Javascript",
		optionC: "JSX",
		optionD: "ES6",
		asnwer: "optionC",
	},
];
